### ISSUE TITLE
Getting the reshape error whilw using the same dataset

### ISSUE THREAD

**Issue by ShailendraLowanshi24** [BakingBrains/Generation_of_Data_using_GAN#10]

**Comment by ShailendraLowanshi24** [comment]
ValueError: could not broadcast input array from shape (96,96,3) into shape (96,96)

Getting the error whilw using the same dataset

**Comment by BakingBrains** [comment]
@ShailendraLowanshi24 can delete .npy file in the dataset folder and check again

**Comment by ShailendraLowanshi24** [comment]
I’ve checked and there is no .npy file in dataset.

I’ve tried all the solutions that you have given to other people. But it’s not working.

**Comment by BakingBrains** [comment]
@ShailendraLowanshi24 you can check ProGAN for data generation, this will give a good result

**Comment by BakingBrains** [comment]
@ShailendraLowanshi24 Drop your mail, I will share the code.

**Comment by ShailendraLowanshi24** [comment]
shailendrabfab@gmail.com Thank you for the help

**Comment by ShailendraLowanshi24** [comment]
In the first line of code, in training_binary_path it’s looking for .npy files.
Do you think the error is in that part

**Comment by BakingBrains** [comment]
might be that issue. But whenever I tried to reproduce the same error, I am unable to.

**Comment by ShailendraLowanshi24** [comment]
I’m using the same dataset, still I’m getting that error and even I’m using Colab. 
maybe you can make changes in that code

**Comment by BakingBrains** [comment]
can you share the colab? or Let me check once again.

**Comment by ShailendraLowanshi24** [comment]
https://colab.research.google.com/drive/1bisZW2MySZcFcMcBUv3_Bkw8BlmQ_DCn?usp=sharing

Above is the link for Google colab

**Comment by ShailendraLowanshi24** [comment]
Like you said earlier to check .not file in dataset. 
I don’t think other than training_binary_path, there is use of .npy file
