### ISSUE TITLE
Output problem

### ISSUE THREAD

**Issue by ghazaleh-alizadegan** [BakingBrains/Generation_of_Data_using_GAN#11]
My image is not clear at all, and it gives me only one image, what could be the reason?

**Comment by BakingBrains** [comment]
@Ghazal-alizadegan This is the demo on how can you generate images from GAN. To generate more variety of image please check advanced methods of GAN or the diffusers. https://github.com/huggingface/diffusers

**Comment by ghazaleh-alizadegan** [comment]
ok thanks.
