### ISSUE TITLE
What format do the images have to be in?

### ISSUE THREAD

**Issue by brandonculver** [BakingBrains/Generation_of_Data_using_GAN#4]
I had some pngs, but it doesn't seem to like them.

`ValueError: cannot reshape array of size 2617344 into shape (96,96,3)`

**Comment by BakingBrains** [comment]
There is a numpy file created in your dataset directory which has a shape of (96, 96,3). Try deleting that file and re-run

**Comment by brandonculver** [comment]
It never creates the file, its fails on the first run.

**Comment by brandonculver** [comment]
The error comes after reading the image files, the first value (2617344) seems to be the raw dump of the pngs. The more I have, the larger the number.

**Comment by BakingBrains** [comment]
I need  some more information. Can we connect on linkedin, would be happy to help. My [LinkedIn](https://www.linkedin.com/in/syed-abdul-gaffar-shakhadri-a44111187/)
