### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by orl0v** [BakingBrains/Generation_of_Data_using_GAN#5]
Hello,
Can you try to implement a checkpoint restore? because i am trying to train a big gan and it wont work. i have tried everything. 
thank you

**Comment by BakingBrains** [comment]
Sure, I can do that. Can you please tell what's issue you're facing?

**Comment by orl0v** [comment]
I have tried implementing it by myself but when I stopped the training and restarted it it just started over from 0 I tried over 3 methods from different sources but not one worked

**Comment by BakingBrains** [comment]
Does these methods were successfull in loading the chekpoint? and if it is successful in loading the checkpoint and training then epoch number (starting from 0 again) should not harm, because it has started the training from a saved checkpoint.

**Comment by orl0v** [comment]
It loaded it succefull. I will try it again and if I see the result everything is ok
Thank you

**Comment by orl0v** [comment]
Could you try for yourself to implement it and look if it works for you?

**Comment by BakingBrains** [comment]
Yeah sure, I will try ones.

**Comment by orl0v** [comment]
Thank you very much

**Comment by BakingBrains** [comment]
It is working. I am saving the checkpoint for every 5 epochs and then loading it again, and continuing the training. The epoch number is same but, when it is saving the chekcpoint with different name.

```
checkpoint_dir = '/content/weights'
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt")
checkpoint = tf.train.Checkpoint(generator_optimizer=generator_optimizer,
                                 discriminator_optimizer=discriminator_optimizer,
                                 generator=generator,
                                 discriminator=discriminator)

ckpt_manager = tf.train.CheckpointManager(checkpoint, checkpoint_dir, max_to_keep=5)

# if a checkpoint exists, restore the latest checkpoint.
if ckpt_manager.latest_checkpoint:
  checkpoint.restore(ckpt_manager.latest_checkpoint)
  print ('Latest checkpoint restored!!')
```

This will restore if there are any previous checkpoints.

**Comment by orl0v** [comment]
Thank you. So does the epoch shows the number from zero or from the previous epoch?

**Comment by BakingBrains** [comment]
Epoch starts from zero, if you want it to start from resumed checkpoint you can read the checkpoint name split it to obtain the saved number and give that for the epoch number and continue the training.

**Comment by orl0v** [comment]
thank you very much. you saved me much work!! :)
