### ISSUE TITLE
Can't solve Input 0 of layer "conv2d_5" is incompatible with the layer

### ISSUE THREAD

**Issue by milaomrani** [BakingBrains/Generation_of_Data_using_GAN#6]
I'm having trouble solving this error:

WARNING:tensorflow:Model was constructed with shape (None, 96, 96, 3) for input KerasTensor(type_spec=TensorSpec(shape=(None, 96, 96, 3), dtype=tf.float32, name='conv2d_5_input'), name='conv2d_5_input', description="created by layer 'conv2d_5_input'"), but it was called on an input with incompatible shape (32, 96, 96).

ValueError: in user code:

    File "<ipython-input-7-08dbda42c23d>", line 8, in train_step  *
        real_output = discriminator(images, training=True)
    File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler  **
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.7/dist-packages/keras/engine/input_spec.py", line 227, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" '

    ValueError: Exception encountered when calling layer "sequential_1" (type Sequential).
    
    Input 0 of layer "conv2d_5" is incompatible with the layer: expected min_ndim=4, found ndim=3. Full shape received: (32, 96, 96)
    
    Call arguments received:
      • inputs=tf.Tensor(shape=(32, 96, 96), dtype=float32)
      • training=True
      • mask=None

**Comment by BakingBrains** [comment]
@milaomrani can you please delete the .npy file created in the dataset folder and re-run again. Let me know if it is solved.

**Comment by milaomrani** [comment]
I restart the kernel, and rerun... 

still -->

Input 0 of layer sequential_1 is incompatible with the layer: : expected min_ndim=4, found ndim=3. Full shape received: (32, 64, 64)

**Comment by milaomrani** [comment]
Sorry, the reason for that error was that I did not add the IMAGE_CHANNEL, 

however, once I add it, again, I get the same error,

 cannot reshape array of size 16384000 into shape (64,64,3)

Besides, all images of my dataset are  in 640*640 .

![reshapeError](https://user-images.githubusercontent.com/50385765/147899393-12d59298-bb47-428d-904a-ffcfc99cda38.png)

**Comment by BakingBrains** [comment]
@milaomrani The dimensions should be 4, but here you're getting only 3. Can you please check if you set all these parameters properly

```
GENERATE_RES = 3 # Generation resolution factor 
# (1=32, 2=64, 3=96, 4=128, etc.)
GENERATE_SQUARE = 32 * GENERATE_RES # rows/cols (should be square)
IMAGE_CHANNELS = 3

# Preview image 
PREVIEW_ROWS = 4
PREVIEW_COLS = 7
PREVIEW_MARGIN = 16

# Size vector to generate images from
SEED_SIZE = 100

# Configuration
DATA_PATH = ''
EPOCHS = 50
BATCH_SIZE = 32
BUFFER_SIZE = 60000
```

**Comment by BakingBrains** [comment]
Also you can check the [progressive GAN](https://github.com/BakingBrains/Progressive_GAN-ProGAN-_implementation) repo, It generates high quality images and the training steps are pretty straight.

**Comment by milaomrani** [comment]
@BakingBrains 

All are set.

![reshapeError](https://user-images.githubusercontent.com/50385765/147899718-2a2aba10-191d-4779-aa49-affa08fd6777.png)

**Comment by BakingBrains** [comment]
@milaomrani After ```  training_data = np.reshape(training_data,(-1,GENERATE_SQUARE,
            GENERATE_SQUARE,IMAGE_CHANNELS))```  variable add ```   training_data = training_data.astype(np.float32) ``` and then ```  training_data = training_data / 127.5 - 1.```  this line and check.

**Comment by milaomrani** [comment]
It's added, but the error I get is in the  training_data = np.reshape(training_data,(-1,GENERATE_SQUARE,GENERATE_SQUARE,IMAGE_CHANNELS))

**Comment by BakingBrains** [comment]
can you please check what is the shape of training_data? (training_data.shape)

**Comment by milaomrani** [comment]
It reads it as a list :0

'list' object has no attribute 'shape'

**Comment by BakingBrains** [comment]
@milaomrani hope you resolved the issue.
