### ISSUE TITLE
How to save output images separately?

### ISSUE THREAD

**Issue by skuma307** [BakingBrains/Generation_of_Data_using_GAN#7]
Hi, Thanks for this amazing implementation of GAN. I am facing an issue. How can I save the generated images separately one by one in the output folder? Can you guide me on that? Thanks in adavance.

**Comment by BakingBrains** [comment]
Hello @skuma307 drop your mail ID, I will share the advanced version of the code (which save each generated image separately)

**Comment by skuma307** [comment]
Sure @BakingBrains , Please find it here: sonu1000raw@gmail.com. Really appreciate your kindness and support. Thanks
